{ 
 "items": [
{type: "Publication",
label : "SW-Store: a Vertically Partitioned DBMS for Semantic Web Data Management",
id : "0",
booktitle : "VLDB Journal",
"pub-type" : "article",
year : "2009",
month : "4",
url :"http://db.csail.mit.edu/pubs/swstore.pdf",
author : ["Daniel Abadi", "Adam Marcus", "Samuel Madden", "Katherine Hollenbach"]
},
{type: "Publication",
label : "Wishbone: Proﬁle-based Partitioning for Sensornet Applications",
id : "1",
booktitle : "Proceedings of NSDI",
"pub-type" : "inproceedings",
year : "2009",
month : "",
url :"http://db.csail.mit.edu/pubs/wishbone-nsdi09.pdf",
author : ["Ryan Newton", "Sivan Toledo", "Lewis Girod", "Hari Balakrishnan", "Samuel Madden"]
},
{type: "Publication",
label : "ZStream: A Cost-based Query Processor for Adaptively  Detecting Composite Events",
id : "2",
booktitle : "Proceedings of SIGMOD",
"pub-type" : "inproceedings",
year : "2009",
month : "",
url :"http://db.csail.mit.edu/pubs/xstream-sigmod09.pdf",
author : ["Yuan Mei", "Samuel Madden"]
},
{type: "Publication",
label : "Top-k Queries on Uncertain Data: On Score Distribution  and Typical Answers",
id : "3",
booktitle : "Proceedings of SIGMOD",
"pub-type" : "inproceedings",
year : "2009",
month : "",
url :"http://db.csail.mit.edu/pubs/sigmod308-ge.pdf",
author : ["Tingjian Ge", "Stan Zdonik", "Samuel Madden"]
},
{type: "Publication",
label : "A Comparison of Approaches to Large-Scale Data Analysis",
id : "4",
booktitle : "Proceedings of SIGMOD",
"pub-type" : "inproceedings",
year : "2009",
month : "",
url :"http://db.csail.mit.edu/pubs/benchmarks-sigmod09.pdf",
author : ["Andrew Pavlo", "Erik Paulson", "Alexander Rasin", "Daniel Abadi", "David DeWitt", "Samuel Madden", "Michael Stonebraker"]
},
{type: "Publication",
label : "The Case for RodentStore, an Adaptive, Declarative Storage System",
id : "5",
booktitle : "Proceedings of CIDR (Perspectives Track)",
"pub-type" : "inproceedings",
year : "2009",
month : "",
url :"http://db.csail.mit.edu/pubs/AdaptiveStorage.pdf",
author : ["Philippe Cudre-Mauroux", "Eugene Wu", "Samuel Madden"]
},
{type: "Publication",
label : "The Emergence of a Networking Primitive inWireless Sensor Networks",
id : "6",
booktitle : "Communications of the ACM",
"pub-type" : "article",
year : "2008",
month : "7",
url :"http://db.csail.mit.edu/pubs/p99-levis.pdf",
author : ["Philip Levis", "Eric Brewer", "David Culler", "David Gay", "Samuel Madden", "Neil Patel", "Joseph Polastre", "Scott Shenker", "Robert Szewczyk", "Alec Woo"]
},
{type: "Publication",
label : "Cabernet: Vehicular Content Delivery Using WiFi",
id : "7",
booktitle : "Proceedings of MobiCom",
"pub-type" : "inproceedings",
year : "2008",
month : "",
url :"http://db.csail.mit.edu/pubs/cabernet-final.pdf",
author : ["Jakob Eriksson", "Hari Balakrishnan", "Samuel Madden"]
},
{type: "Publication",
label : "H-Store: A High-Performance, Distributed Main Memory Transaction Processing System",
id : "8",
booktitle : "Proceedings of VLDB",
"pub-type" : "demo",
year : "2008",
note: "Demo.",
month : "",
url :"http://db.csail.mit.edu/pubs/final_hstore.pdf",
author : ["Robert Kallman", "Hideaki Kimura", "Jonathan Natkins", "Andrew Pavlo", "Alex Rasin", "Stan Zdonik", "Evan Jones", "Yang Zhang", "Samuel Madden", "Michael Stonebraker", "John Hugg", "Daniel Abadi"]
},
{type: "Publication",
label : "Performance Proﬁling with EndoScope, an Acquisitional Software Monitoring Framework",
id : "9",
booktitle : "Proceedings of VLDB",
"pub-type" : "inproceedings",
year : "2008",
month : "",
url :"http://db.csail.mit.edu/pubs/asp-cr.pdf",
author : ["Alvin Cheung", "Samuel Madden"]
},
{type: "Publication",
label : "The Pothole Patrol: Using a Mobile Sensor Network for Road Surface Monitoring ",
id : "10",
booktitle : "Proceedings of MobiSys",
"pub-type" : "inproceedings",
year : "2008",
month : "",
url :"http://db.csail.mit.edu/pubs/mobisys08.pdf",
author : ["Jakob Eriksson", "Lewis Girod", "Bret Hull", "Ryan Newton", "Hari Balakrishnan", "Samuel Madden"]
},
{type: "Publication",
label : "Design and Evaluation of a Compiler for Embedded Stream Programs",
id : "11",
booktitle : "Proceedings of Conference on Languages, Compilers, and Tools for Embedded Systems (LCTES)",
"pub-type" : "inproceedings",
year : "2008",
month : "",
url :"http://db.csail.mit.edu/pubs/newton-lctes08.pdf",
author : ["Ryan Newton", "Lewis Girod", "Michael Craig", "Samuel Madden", "Greg Morrisett"]
},
{type: "Publication",
label : "Wireless Sensor Network for Monitoring a Large Scale Infrastructure Systems in Boston, USA",
id : "12",
booktitle : "Data Requirements for Integrated Urban Water Management",
"pub-type" : "bookchapter",
year : "2008",
note: "Book Chapter.",
month : "",
author : ["Ivan Stoianov", "C. Maksimovic", "Lama Nachman", "Andrew Whittle", "Samuel Madden", "Ralph Kling"]
},
{type: "Publication",
label : "VoxNet: An Interactive, Rapid-Deployable Acoustic Monitoring Platform",
id : "13",
booktitle : "Proceedings of IPSN SPOTS",
"pub-type" : "inproceedings",
year : "2008",
month : "",
url :"http://nms.csail.mit.edu/~girod/ipsn08.pdf",
author : ["Michael Allen", "Lewis Girod", "Ryan Newton", "Samuel Madden", "Daniel T. Blumstein", "Deborah Estrin"]
},
{type: "Publication",
label : "Representing and Querying Regression Models in a DBMS",
id : "14",
booktitle : "Proceedings of SIGMOD",
"pub-type" : "inproceedings",
year : "2008",
month : "",
url :"http://db.csail.mit.edu/pubs/fp438-thiagarajan.pdf",
author : ["Arvind Thiagarajan", "Samuel Madden"]
},
{type: "Publication",
label : "OLTP Through the Looking Glass, And What We Found There",
id : "15",
booktitle : "Proceedings of SIGMOD",
"pub-type" : "inproceedings",
year : "2008",
month : "",
url :"http://db.csail.mit.edu/pubs/fp571-harizopoulos.pdf",
author : ["Stavros Harizopoulos", "Daniel Abadi", "Samuel Madden", "Michael Stonebraker"]
},
{type: "Publication",
label : "Column-Stores vs. Row-Stores: How Different Are They Really?",
id : "16",
booktitle : "Proceedings of SIGMOD",
"pub-type" : "inproceedings",
year : "2008",
month : "",
url :"http://db.csail.mit.edu/pubs/ssbm.pdf",
author : ["Daniel Abadi", "Samuel Madden", "Nabil Hachem"]
},
{type: "Publication",
label : "XStream: A Signal-Oriented Data Stream Management System",
id : "17",
booktitle : "Proceedings of ICDE",
"pub-type" : "inproceedings",
year : "2008",
month : "",
url :"http://db.csail.mit.edu/pubs/icde08.pdf",
author : ["Lewis Girod", "Yuan Mei", "Ryan Newton", "Stanislav Rost", "Arvind Thiagarajan", "Hari Balakrishnan", "Samuel Madden"]
},
{type: "Publication",
label : "Fault-Tolerance in the Borealis Distributed Stream Processing System",
id : "18",
booktitle : "TODS",
"pub-type" : "article",
year : "2008",
month : "",
url :"http://db.csail.mit.edu/pubs/magda-tods07.pdf",
author : ["Magdalena Balazinska", "Hari Balakrishnan", "Samuel Madden", "Michael Stonebraker"]
},
{type: "Publication",
label : "Thinking Big About Tiny Databases",
id : "19",
booktitle : "IEEE Data Engineering Bulletin 30(3)",
"pub-type" : "invited",
year : "2007",
month : "",
url :"http://sites.computer.org/debull/A07Sept/madden.pdf",
author : ["Michael Franklin", "Joseph Hellerstein", "Samuel Madden"]
},
{type: "Publication",
label : "The End of an Architectural Era (It’s Time for a Complete Rewrite) ",
id : "20",
booktitle : "Proceedings of VLDB",
"pub-type" : "inproceedings",
year : "2007",
month : "",
url :"http://db.csail.mit.edu/pubs/vldb-07-hstore-final.pdf",
author : ["Michael Stonebraker", "Samuel Madden", "Daniel Abadi", "Stavros Harizopoulos", "Nabil Hachem", "Pat Helland"]
},
{type: "Publication",
label : "Tolerating Byzantine Faults in Transaction Processing Systems using Commit Barrier Scheduling",
id : "21",
booktitle : "Proceedings of SOSP",
"pub-type" : "inproceedings",
year : "2007",
month : "",
url :"http://db.csail.mit.edu/pubs/hrdb.pdf",
author : ["Ben Vandiver", "Hari Balakrishnan", "Samuel Madden", "Barbara Liskov"]
},
{type: "Publication",
label : "Scalable Semantic Web Data Management Using Vertical Partitioning (Best Paper Award)",
id : "22",
booktitle : "Proceedings of VLDB",
"pub-type" : "inproceedings",
year : "2007",
month : "",
url :"http://db.csail.mit.edu/pubs/abadirdf.pdf",
author : ["Daniel Abadi", "Adam Marcus", "Samuel Madden", "Katherine Hollenbach"]
},
{type: "Publication",
label : "Mobiscopes for Human Spaces ",
id : "23",
booktitle : "Pervasive Computing",
"pub-type" : "article",
year : "2007",
month : "",
url :"http://db.csail.mit.edu/pubs/b2est-final.pdf",
author : ["Tarek Abdelzaher", "Yaw Anokwa", "Péter Boda", "Jeff Burke", "Deborah Estrin", "Leonidas Guibas", "Aman Kansal", "Samuel Madden", "Jim Reich"]
},
{type: "Publication",
label : "PIPENET:  A Wireless Sensor Network for Pipeline Monitoring",
id : "24",
booktitle : "Proceedings of IPSN",
"pub-type" : "inproceedings",
year : "2007",
month : "",
url :"http://db.csail.mit.edu/pubs/ipsn278-nachman.pdf",
author : ["Ivan Stoianov", "Lama Nachman", "Samuel Madden", "Timur Tokmouline"]
},
{type: "Publication",
label : "Information Survival Threshold in Sensor and P2P Networks",
id : "25",
booktitle : "Proceedings of INFOCOM",
"pub-type" : "inproceedings",
year : "2007",
month : "",
url :"http://www.cs.cmu.edu/~christos/PUBLICATIONS/infocomm-sensors.pdf",
author : ["Jure Leskovec", "Deepayan Chakrabarti", "Christos Faloutsos", "Samuel Madden", "Carlos Guestrin", "Michalis Faloutsos"]
},
{type: "Publication",
label : "The Case for a Signal-Oriented Data Stream Management System",
id : "26",
booktitle : "Proceedings of CIDR",
"pub-type" : "inproceedings",
year : "2007",
month : "",
url :"http://db.csail.mit.edu/pubs/cidr07.pdf",
author : ["Lewis Girod", "Yuan Mei", "Ryan Newton", "Stanislav Rost", "Arvind Thiagarajan", "Hari Balakrishnan", "Samuel Madden"]
},
{type: "Publication",
label : "ICEDB: Intermittently Connected Continuous Query Processing",
id : "27",
booktitle : "Proceedings of ICDE",
"pub-type" : "inproceedings",
year : "2007",
month : "",
url :"http://db.csail.mit.edu/pubs/icde07cr.pdf",
author : ["Yang Zhang", "Bret Hull", "Hari Balakrishnan", "Samuel Madden"]
},
{type: "Publication",
label : "Materialization Strategies in a Column-Oriented DBMS ",
id : "28",
booktitle : "Proceedings of ICDE",
"pub-type" : "inproceedings",
year : "2007",
month : "",
url :"http://db.csail.mit.edu/pubs/abadi-icde07cr.pdf",
author : ["Daniel Abadi", "Daniel Myers", "David DeWitt", "Samuel Madden"]
},
{type: "Publication",
label : "Scoop: An Adaptive Indexing Scheme for Stored Data in Sensor Networks",
id : "29",
booktitle : "Proceedings of ICDE",
"pub-type" : "poster",
year : "2007",
note: "Poster.",
month : "",
url :"http://db.csail.mit.edu/pubs/scoop-icde07cr.pdf",
author : ["Thomer Gil", "Samuel Madden"]
},
{type: "Publication",
label : "The CarTel Mobile Sensor Computing System (Best Demo Award)",
id : "30",
booktitle : "Proceedings of SenSys",
"pub-type" : "demo",
year : "2006",
note: "Demo.",
month : "",
author : ["Yang Zhang", "Eugene Shih", "Allen Miu", "Bret Hull", "Michel Goraczko", "Jakob Eriksson", "Vladimir Bychkovskiy", "Samuel Madden", "Hari Balakrishnan"]
},
{type: "Publication",
label : "An Energy-efficient Querying Framework for Detecting Node Similarities in Sensor Networks",
id : "31",
booktitle : "Proceedings of ACM/IEEE International Symposium on Modeling, Analysis and Simulation in Sensor Networks (MSWiM)",
"pub-type" : "inproceedings",
year : "2006",
month : "",
url :"http://db.csail.mit.edu/pubs/MSWIM1.pdf",
author : ["Daniela Tulone", "Samuel Madden"]
},
{type: "Publication",
label : "Data Management in the CarTel Mobile Sensor Computing System",
id : "32",
booktitle : "Proceedings of SIGMOD",
"pub-type" : "demo",
year : "2006",
note: "Demo.",
month : "",
url :"http://db.csail.mit.edu/pubs/submit.pdf",
author : ["Vladimir Bychkovskiy", "Kevin Chen", "Michel Goraczko", "Hongyi Hu", "Bret Hull", "Allen Miu", "Eugene Shih", "Yang Zhang", "Hari Balakrishnan", "Samuel Madden"]
},
{type: "Publication",
label : "CarTel: A Distributed Mobile Sensor Computing System",
id : "33",
booktitle : "Proceedings of SenSys",
"pub-type" : "inproceedings",
year : "2006",
month : "",
url :"http://db.csail.mit.edu/pubs/sensys06.pdf",
author : ["Bret Hull", "Vladimir Bychkovskiy", "Kevin Chen", "Michel Goraczko", "Eugene Shih", "Yang Zhang", "Hari Balakrishnan", "Samuel Madden"]
},
{type: "Publication",
label : "A Measurement Study of Vehicular Internet Access Using Unplanned 802.11 Networks (Best Paper Award)",
id : "34",
booktitle : "Proceedings of MOBICOM",
"pub-type" : "inproceedings",
year : "2006",
month : "",
url :"http://db.csail.mit.edu/pubs/mobicom06.pdf",
author : ["Vladimir Bychkovskiy", "Bret Hull", "Allen Miu", "Hari Balakrishnan", "Samuel Madden"]
},
{type: "Publication",
label : "Performance Tradeoffs in Read-Optimized Databases",
id : "35",
booktitle : "Proceedings of VLDB",
"pub-type" : "inproceedings",
year : "2006",
month : "",
url :"http://db.csail.mit.edu/pubs/harizopoulosVLDB06.pdf",
author : ["Stavros Harizopoulos", "Velen Liang", "Daniel Abadi", "Samuel Madden"]
},
{type: "Publication",
label : "An Integrated Approach to Recovery and High Availability in an Updatable, Distributed Data Warehouse",
id : "36",
booktitle : "Proceedings of VLDB",
"pub-type" : "inproceedings",
year : "2006",
month : "",
url :"http://db.csail.mit.edu/pubs/vldb06-v5.pdf",
author : ["Edmond Lau", "Samuel Madden"]
},
{type: "Publication",
label : "Compression in Column Oriented Databases",
id : "37",
booktitle : "Proceedings of SIGMOD",
"pub-type" : "inproceedings",
year : "2006",
month : "",
url :"http://db.csail.mit.edu/pubs/915.pdf",
author : ["Daniel Abadi", "Samuel Madden"]
},
{type: "Publication",
label : "MauveDB: Supporting Model-Based User Views in Database Systems",
id : "38",
booktitle : "Proceedings of SIGMOD",
"pub-type" : "inproceedings",
year : "2006",
month : "",
url :"http://db.csail.mit.edu/pubs/sigmod06-mauvedb.pdf",
author : ["Amol Deshpande", "Samuel Madden"]
},
{type: "Publication",
label : "A Measurement-based Analysis of the Interaction Between Network Layers in TinyOS",
id : "39",
booktitle : "Proceedings of EWSN",
"pub-type" : "inproceedings",
year : "2006",
month : "",
url :"http://db.csail.mit.edu/pubs/ewsn_cameraready_2.pdf",
author : ["Umberto Malesci", "Samuel Madden"]
},
{type: "Publication",
label : "PAQ: Time series forecasting for approximate query answering in sensor networks",
id : "40",
booktitle : "Proceedings of EWSN",
"pub-type" : "inproceedings",
year : "2006",
month : "",
url :"http://db.csail.mit.edu/pubs/EWSN1.pdf",
author : ["Daniela Tulone", "Samuel Madden"]
},
{type: "Publication",
label : "Model-based Approximate Querying in Sensor Networks",
id : "41",
booktitle : "VLDB Journal",
"pub-type" : "article",
year : "2005",
month : "11",
url :"http://db.lcs.mit.edu/madden/html/vldbjournal.pdf",
author : ["Amol Deshpande", "Carlos Guestrin", "Samuel Madden", "Joseph Hellerstein", "Wei Hong"]
},
{type: "Publication",
label : "Resource-Aware Wireless Sensor-Actuator Networks",
id : "42",
booktitle : "IEEE Data Engineering Bulletin 28(1)",
"pub-type" : "invited",
year : "2005",
month : "",
url :"http://db.lcs.mit.edu/madden/html/de_bulletin05.pdf",
author : ["Amol Deshpande", "Carlos Guestrin", "Samuel Madden"]
},
{type: "Publication",
label : "REED: Robust, Efficient Filtering and Event Detection in Sensor Networks",
id : "43",
booktitle : "Proceedings of VLDB",
"pub-type" : "inproceedings",
year : "2005",
month : "",
url :"http://db.lcs.mit.edu/madden/html/reed_cr4.pdf",
author : ["Daniel Abadi", "Samuel Madden", "Wolfgang Lindner"]
},
{type: "Publication",
label : "C-Store: A Column-oriented DBMS ",
id : "44",
booktitle : "Proceedings of VLDB",
"pub-type" : "inproceedings",
year : "2005",
month : "",
url :"http://db.lcs.mit.edu/madden/html/vldb_cr5.pdf",
author : ["Michael Stonebraker", "Daniel Abadi", "Adam Batkin", "Xuedong Chen", "Mitch Cherniack", "Miguel Ferreira", "Edmond Lau", "Amerson Lin", "Samuel Madden", "Elizabeth O’Neil", "Pat O’Neil", "Alex Rasin", "Nga Tran", "Stan Zdonik"]
},
{type: "Publication",
label : "Fault-Tolerance in the Borealis Distributed Stream Processing System",
id : "45",
booktitle : "Proceedings of SIGMOD",
"pub-type" : "inproceedings",
year : "2005",
month : "",
url :"http://nms.lcs.mit.edu/papers/borealis-sigmod05.pdf",
author : ["Magdalena Balazinska", "Hari Balakrishnan", "Samuel Madden", "Michael Stonebraker"]
},
{type: "Publication",
label : "TASK: Sensor Network in a Box",
id : "46",
booktitle : "Proceedings of European Workshop on Sensor Networks",
"pub-type" : "inproceedings",
year : "2005",
month : "",
url :"http://db.lcs.mit.edu/madden/html/task-ewsn05.pdf",
author : ["Phil Buonadonna", "Joseph Hellerstein", "Wei Hong", "David Gay", "Samuel Madden"]
},
{type: "Publication",
label : "Using Probabilistic Models for Data Management in Acquisitional Environments",
id : "47",
booktitle : "Proceedings of CIDR",
"pub-type" : "inproceedings",
year : "2005",
month : "",
url :"http://db.lcs.mit.edu/madden/html/cidr187.pdf",
author : ["Amol Deshpande", "Carlos Guestrin", "Samuel Madden"]
},
{type: "Publication",
label : "TinyDB: An Acquisitional Query Processing System for Sensor Networks",
id : "48",
booktitle : "TODS",
"pub-type" : "article",
year : "2005",
month : "",
url :"http://db.lcs.mit.edu/madden/html/tinydb_tods_final.pdf",
author : ["Samuel Madden", "Michael Franklin", "Joseph Hellerstein", "Wei Hong"]
},
{type: "Publication",
label : "Exploiting Correlated Attributes in Acquisitional Query Processing",
id : "49",
booktitle : "Proceedings of ICDE",
"pub-type" : "inproceedings",
year : "2005",
month : "",
url :"http://db.lcs.mit.edu/madden/html/deshpandea_correlated_378-new.pdf",
author : ["Amol Deshpande", "Carlos Guestrin", "Samuel Madden", "Wei Hong"]
},
{type: "Publication",
label : "Data Management Issues in Periodically Disconnected Sensor Networks",
id : "50",
booktitle : "Proceedings of Workshop on Sensor Networks at Informatik",
"pub-type" : "inproceedings",
year : "2004",
month : "",
url :"http://db.lcs.mit.edu/madden/html/disconnected-informatik-2004.pdf",
author : ["Wolfgang Lindner", "Samuel Madden"]
},
{type: "Publication",
label : "Distributed Regression: an Efficient Framework for Modeling Sensor Network Data",
id : "51",
booktitle : "Proceedings of IPSN",
"pub-type" : "inproceedings",
year : "2004",
month : "",
url :"http://db.lcs.mit.edu/madden/html/dr.pdf",
author : ["Carlos Guestrin", "Peter Bodik", "Romain Thibaux", "Mark Paskin", "Samuel Madden"]
},
{type: "Publication",
label : " Query Processing In Sensor Networks",
id : "52",
booktitle : "Pervasive Computer",
"pub-type" : "article",
year : "2004",
month : "",
url :"http://db.lcs.mit.edu/madden/html/pervasive04.pdf",
author : ["Johannes Gehrke", "Samuel Madden"]
},
{type: "Publication",
label : "Model Driven Data Acquisition in Sensor Networks. (Best Paper Award)",
id : "53",
booktitle : "Proceedings of VLDB",
"pub-type" : "inproceedings",
year : "2004",
month : "",
url :"http://db.lcs.mit.edu/madden/html/vldb04.pdf",
author : ["Amol Deshpande", "Carlos Guestrin", "Samuel Madden", "Joseph Hellerstein", "Wei Hong"]
},
{type: "Publication",
label : "The Emergence of Networking Abstractions and Techniques in TinyOS",
id : "54",
booktitle : "Proceedings of NSDI",
"pub-type" : "inproceedings",
year : "2004",
month : "",
url :"http://db.lcs.mit.edu/madden/html/tinyos-nsdi04.pdf",
author : ["Philip Levis", "Samuel Madden", "David Gay", "Joseph Polastre", "Robert Szewczyk", "Alec Woo", "Eric Brewer", "David Culler"]
},
{type: "Publication",
label : "Networking Support for Query Processing in Sensor Networks",
id : "55",
booktitle : "CACM Special Issue on Sensor Networks",
"pub-type" : "article",
year : "2004",
month : "",
url :"http://db.csail.mit.edu/pubs/p47-woo.pdf",
author : ["Alec Woo", "Samuel Madden", "Ramesh Govindan"]
},
{type: "Publication",
label : "An Integrated Framework for Sensor Networks and Data Stream Management Systems.",
id : "56",
booktitle : "Proceedings of VLDB",
"pub-type" : "demo",
year : "2004",
note: "Demo.",
month : "",
author : ["Daniel Abadi", "Wolfgang Lindner", "Samuel Madden", "Jorg Schuler"]
},
{type: "Publication",
label : "The Design and Evaluation of a Query Processing Architecture for Sensor Networks",
id : "57",
booktitle : "UC Berkeley Ph.D. Thesis",
"pub-type" : "phdthesis",
year : "2003",
month : "",
url :"http://db.lcs.mit.edu/madden/html/thesis.pdf",
author : ["Samuel Madden"]
},
{type: "Publication",
label : "The Design of an Acquisitional Query Processor for Sensor Networks",
id : "58",
booktitle : "Proceedings of SIGMOD",
"pub-type" : "inproceedings",
year : "2003",
month : "",
url :"http://db.lcs.mit.edu/madden/html/acqp.pdf",
author : ["Samuel Madden", "Michael Franklin", "Joseph Hellerstein", "Wei Hong"]
},
{type: "Publication",
label : "Beyond Average: Towards Sophisticated Sensing with Queries",
id : "59",
booktitle : "Proceedings of IPSN",
"pub-type" : "inproceedings",
year : "2003",
month : "",
url :"http://db.lcs.mit.edu/madden/html/beyond_average_ipsn.pdf",
author : ["Joseph Hellerstein", "Wei Hong", "Samuel Madden", "Kyle Stanek"]
},
{type: "Publication",
label : "TelegraphCQ: Continuous Dataflow Processing for an Uncertain World",
id : "60",
booktitle : "Proceedings of CIDR",
"pub-type" : "inproceedings",
year : "2003",
month : "",
url :"http://db.lcs.mit.edu/madden/html/TCQcidr03.pdf",
author : ["Sirish Chandrasekaran", "Owen Cooper", "Amol Deshpande", "Michael Franklin", "Joseph Hellerstein", "Wei Hong", "Sailesh Krishnamurthy", "Samuel Madden", "Vijayshankar Raman", "Fred Reiss", "Mehul Shah"]
},
{type: "Publication",
label : "TelegraphCQ: An Architectural Status Report",
id : "61",
booktitle : "IEEE Data Engineering Bulletin 26(1)",
"pub-type" : "invited",
year : "2003",
month : "",
url :"http://db.lcs.mit.edu/madden/html/deissue-b.pdf",
author : ["Sailesh Krishnamurthy", "Sirish Chandrasekaran", "Owen Cooper", "Amol Deshpande", "Michael Franklin", "Joseph Hellerstein", "Wei Hong", "Samuel Madden", "Fred Reiss", "Mehul Shah"]
},
{type: "Publication",
label : "The Sensor Spectrum: Technology, Trends, and Requirements",
id : "62",
booktitle : "SIGMOD Record",
"pub-type" : "article",
year : "2003",
month : "",
url :"http://db.lcs.mit.edu/madden/html/sensorspectrum.pdf",
author : ["Joseph Hellerstein", "Wei Hong", "Samuel Madden"]
},
{type: "Publication",
label : "Distributed Regression in Sensor Networks. ",
id : "63",
booktitle : "Proceedings of NIPS",
"pub-type" : "poster",
year : "2003",
note: "Poster.",
month : "",
url :"http://db.lcs.mit.edu/madden/html/regression-poster.pdf",
author : ["Carlos Guestrin", "Peter Bodik", "Romain Thibaux", "Mark Paskin", "Samuel Madden"]
},
{type: "Publication",
label : "TAG: a Tiny AGgregation Service for Ad-Hoc Sensor Networks",
id : "64",
booktitle : "Proceedings of OSDI",
"pub-type" : "inproceedings",
year : "2002",
month : "",
url :"http://db.lcs.mit.edu/madden/html/madden_tag.pdf",
author : ["Samuel Madden", "Michael Franklin", "Joseph Hellerstein", "Wei Hong"]
},
{type: "Publication",
label : " Continuously Adaptive Continuous Queries over Streams",
id : "65",
booktitle : "Proceedings of SIGMOD",
"pub-type" : "inproceedings",
year : "2002",
month : "",
url :"http://db.lcs.mit.edu/madden/html/madden_cacq_final.pdf",
author : ["Samuel Madden", "Mehul Shah", "Joseph Hellerstein", "Vijayshankar Raman"]
},
{type: "Publication",
label : "Supporting Aggregate Queries Over Ad-Hoc Wireless Sensor Networks",
id : "66",
booktitle : "Proceedings of Workshop on Mobile Computing and Systems Applications",
"pub-type" : "inproceedings",
year : "2002",
month : "",
url :"http://db.lcs.mit.edu/madden/html/madden_aggregation.pdf",
author : ["Samuel Madden", "Robert Szewczyk", "Michael Franklin", "David Culler"]
},
{type: "Publication",
label : "Fjording the Stream: An Architecture for Queries over Streaming Sensor Data",
id : "67",
booktitle : "Proceedings of ICDE",
"pub-type" : "inproceedings",
year : "2002",
month : "4",
url :"http://db.lcs.mit.edu/madden/html/madden_fjords.pdf",
author : ["Samuel Madden", "Michael Franklin"]
},
{type: "Publication",
label : "Queries over Ad-Hoc Sensor Networks.",
id : "68",
booktitle : "Proceedings of SIGMOD",
"pub-type" : "demo",
year : "2002",
note: "Demo.",
month : "",
author : ["Samuel Madden", "Joseph Hellerstein"]
},
{type: "Publication",
label : "TOADS: A Two-Dimensional, Open-Ended Architectural Database System",
id : "69",
booktitle : "Presence",
"pub-type" : "article",
year : "2001",
month : "",
author : ["Samuel Madden", "Thomas Weigand"]
},
{type: "Publication",
label : " Java Support for Data-intensive Systems: Experiences Building the Telegraph Dataflow System",
id : "70",
booktitle : "SIGMOD Record",
"pub-type" : "invited",
year : "2001",
month : "",
url :"http://db.lcs.mit.edu/madden/html/javapaper.pdf",
author : ["Mehul Shah", "Samuel Madden", "Michael Franklin", "Joseph Hellerstein"]
},
{type: "Publication",
label : "Adaptive Query Processing: Technology in Evolution",
id : "71",
booktitle : "IEEE Data Engineering Bulletin 23(2)",
"pub-type" : "invited",
year : "2000",
month : "",
author : ["Joseph Hellerstein", "Michael Franklin", "Sirish Chandrasekaran", "Amol Deshpande", "Kris Hildrum", "Samuel Madden", "Vijayshankar Raman", "Mehul Shah"]
},
{type: "Publication",
label : "TOADS: A Two-Dimensional, Open-Ended Architectural Database System",
id : "72",
booktitle : "MIT EECS M.Eng. Thesis",
"pub-type" : "mastersthesis",
year : "1999",
month : "",
author : ["Samuel Madden"]
},
]}
